### ISSUE TITLE
admissionregistration.k8s.io/v1alpha1 deprecated in kube > v1.9

### ISSUE THREAD

**Issue by zdhamasha** [yahoo/k8s-namespace-guard#6]
* The former **ExternalAdmissionHookConfiguration** type has been replaced by the incompatible **ValidatingWebhookConfiguration** and **MutatingWebhookConfiguration** types.

**Comment by zdhamasha** [comment]
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8s-namespace-guard
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: k8s-namespace-guard 
      namespace: default
  failurePolicy: Fail
  sideEffects: None
  timeoutSeconds: 10
  name: validate.nginx.ingress.kubernetes.io
  rules:
    - operations:
        - DELETE
      apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - namespaces
```
